// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Hello, Yogesh! you are on Home Page",
                      className: "font-semibold dark:text-white"
                    }),
                JsxRuntime.jsx("a", {
                      children: "profile page",
                      className: "text-blue-600 underline",
                      href: "/profile"
                    })
              ],
              className: "py-5 px-10 flex gap-3"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
