// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Profile(props) {
  var user = props.user;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Name : ",
                              className: "font-bold dark:text-white"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: user.name,
                              className: "font-bold dark:text-white"
                            })
                      ],
                      className: "flex gap-3"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Company : ",
                              className: "font-bold dark:text-white"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: user.company,
                              className: "font-bold dark:text-white"
                            })
                      ],
                      className: "flex gap-3"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Email : ",
                              className: "font-bold dark:text-white"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: user.email,
                              className: "font-bold dark:text-white"
                            })
                      ],
                      className: "flex gap-3"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Antino ID : ",
                              className: "font-bold dark:text-white"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: user.id,
                              className: "font-bold dark:text-white"
                            })
                      ],
                      className: "flex gap-3"
                    }),
                JsxRuntime.jsx("a", {
                      children: "Home Page",
                      className: "text-blue-600 underline",
                      href: "/"
                    })
              ],
              className: " grid grid-cols-2 justify-around gap-3 py-5 px-10"
            });
}

var sameer = {
  name: "Sameer Kumar Rana",
  company: "Antino Labs",
  email: "Sameer.r@antino.io",
  id: 489
};

var yogesh = {
  name: "Yogesh Balodi",
  company: "Antino Labs",
  email: "Yogesh.b@antino.io",
  id: 491
};

var make = Profile;

export {
  sameer ,
  yogesh ,
  make ,
}
/* react/jsx-runtime Not a pure module */
